name: 'fish-shop/run-fishtape-tests'
description: 'A GitHub action for running fishtape tests'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  pattern:
    description: 'File name pattern'
    required: false
    default: '**.fish'
runs:
  using: 'composite'
  steps:
    - uses: fish-shop/install-plugin@v1
      with:
        plugin-manager: fisher
        plugins: jorgebucaran/fishtape
    - name: Install tap-diff
      run: npm install -g tap-diff
      shell: fish {0}
    - name: Run fishtape tests
      run: fishtape ${{ inputs.pattern }} | tap-diff
      shell: fish {0}
